# Generated by Django 5.0.6 on 2024-07-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dress',
            old_name='color',
            new_name='effect',
        ),
    ]
