# Generated by Django 5.0.6 on 2025-06-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device'),
        ('dress', '0002_rename_color_dress_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='dress',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dress',
            name='device',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='effect',
            field=models.IntegerField(choices=[(0, 'Desligado'), (1, 'Estático'), (2, 'Piscar'), (3, 'Cobrinha'), (4, 'Arco-íris')], default=0),
        ),
    ]
