# Generated by Django 5.0.6 on 2025-06-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress', '0003_dress_color_dress_status_alter_dress_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='dress',
            name='effect',
            field=models.IntegerField(choices=[(0, 'Desligado'), (1, 'Estático'), (2, 'Piscar'), (3, 'Cobrinha'), (4, 'Arco-íris'), (5, 'Fogo'), (6, 'Espectro')], default=0),
        ),
    ]
