# Generated by Django 5.0.6 on 2024-07-06 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.CharField(max_length=100, unique=True)),
                ('numero_candidato', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(10)])),
                ('votos_candidato', models.IntegerField(default=0)),
            ],
        ),
    ]
