# Generated by Django 5.0.6 on 2024-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_candidato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voto',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='votos_candidato',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
