# Generated by Django 5.0.6 on 2024-07-16 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_candidato_rainha_candidato_rei'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidata', models.CharField(max_length=100, unique=True)),
                ('numero_candidata', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(10)])),
                ('votos_candidata', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='rainha',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='rei',
        ),
    ]
