# Generated by Django 5.0.6 on 2024-07-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_candidata_remove_candidato_rainha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidata',
            old_name='numero_candidata',
            new_name='numero_da_candidata',
        ),
        migrations.RenameField(
            model_name='candidata',
            old_name='votos_candidata',
            new_name='votos_da_candidata',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='numero_candidato',
            new_name='numero_do_candidato',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='votos_candidato',
            new_name='votos_do_candidato',
        ),
    ]
