# Generated by Django 5.0.6 on 2024-07-19 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_aluno_turma_alter_aluno_votou'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='voto',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
