# Generated by Django 5.0.6 on 2024-07-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_aluno_voto_alter_aluno_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='voto',
            new_name='voto_pessoal',
        ),
    ]
