# Generated by Django 5.0.6 on 2024-07-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_rename_voto_aluno_voto_pessoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='voto_pessoal',
            new_name='candidata',
        ),
        migrations.AddField(
            model_name='aluno',
            name='candidato',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
