# Generated by Django 5.0.6 on 2024-07-27 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_rename_voto_pessoal_aluno_candidata_aluno_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='foto_candidata',
            field=models.ImageField(blank=True, default='defaults/profile_default.png', upload_to='profile_photo/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_candidato',
            field=models.ImageField(blank=True, default='defaults/profile_default.png', upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
