# Generated by Django 5.0.6 on 2025-05-24 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_rename_voto_pessoal_aluno_candidata_aluno_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='descricao_candidata',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='candidata',
            name='foto_candidata',
            field=models.ImageField(blank=True, default='defaults/profile_default.png', upload_to='foto_candidata/'),
        ),
        migrations.AddField(
            model_name='candidata',
            name='turma_candidata',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='candidato',
            name='descricao_candidato',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_candidato',
            field=models.ImageField(blank=True, default='defaults/profile_default.png', upload_to='foto_candidato/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='turma_candidato',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='candidata',
            name='numero_da_candidata',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='numero_do_candidato',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(10)]),
        ),
    ]
