# Generated by Django 5.0.6 on 2025-06-15 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_rename_voto_pessoal_aluno_candidata_aluno_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
