# Generated by Django 5.0.6 on 2024-07-27 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_candidata_foto_candidata_candidato_foto_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='turma_candidata',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='candidato',
            name='turma_candidato',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
