# Generated by Django 5.0.6 on 2025-05-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_candidata_descricao_candidata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
