# Generated by Django 5.0.6 on 2024-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_candidata_turma_candidata_candidato_turma_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidata',
            name='descricao_candidata',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='candidato',
            name='descricao_candidato',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
