# Generated by Django 5.0.6 on 2024-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_candidata_descricao_candidata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidata',
            name='foto_candidata',
            field=models.ImageField(blank=True, default='defaults/foto_candidato.png', upload_to='foto_candidato/'),
        ),
        migrations.AlterField(
            model_name='candidata',
            name='votos_da_candidata',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto_candidato',
            field=models.ImageField(blank=True, default='defaults/foto_candidato.png', upload_to='foto_candidato/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='votos_do_candidato',
            field=models.IntegerField(default=0),
        ),
    ]
