# Generated by Django 5.0.6 on 2025-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='number',
            field=models.CharField(max_length=1),
        ),
    ]
