# Generated by Django 5.0.6 on 2025-06-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_alter_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='candidata',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='candidato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='votou',
            field=models.BooleanField(default=False),
        ),
    ]
