# Generated by Django 5.0.6 on 2025-06-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_alter_aluno_candidata_alter_aluno_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
